### PR TITLE
1 setup repositorys

### LINKED ISSUE #1: Setup Repositorys
**Task title**
Set up Repository

**Task description**
This task involves setting up a new repository. Below are the details of the subtasks :

**Subtasks**
- [x] Update the README with the necessary information.
- [x] Modify repository settings according to the project's requirements.
- [x] Protect the `develop` and `main` branches to prevent accidental changes.
- [x] Add component folders
- [x] upgrade nextjs to the latest version
  
**Screenshots**

Image

### PR DESCRIPTION
**Pull request by Zino0031**
# Related Issue

- Resolve #1

### CODE REVIEW

**Review by HamidAhmidat — APPROVED** [review]
everything seems okay in here.

**Comment by DigitalDeveloperAM** [comment]
This pull request has been checked, Everything running smooth with all features.

**Review by DigitalDeveloperAM — APPROVED** [review]
The last check.

**Review by DigitalDeveloperAM — APPROVED** [review]
This pull request has been checked, Everything running smooth with all features.

**Review by melissasidisid — COMMENTED** [review]
yeah the same for me seems ok

**Review by MenarSelamet — APPROVED** [review]

**Pull request merged**
